### ISSUE TITLE
Support custom date/time formats

### ISSUE THREAD

**Issue by harpchad** [Macmod/godap#6]
Allow the user to configure the date/time formatting. Possibly offer a few pre-defined options and try anything else as a go time format string?

Formats:
- EU: "02/01/2006 15:04:05"
- US: "01/02/2006 15:04:05"
- ISO8601: "2006-01-02 15:04:05"
- "20060102 150405"

example:
--timefmt=US
--timefmt=ISO8601
--timefmt="20060102 150405"

**Comment by Macmod** [comment]
Great idea! 🥇 I'll review the PR 😃

**Comment by Macmod** [comment]
Merged 👍
